### PR TITLE
Cleanup round 2

### PR DESCRIPTION
**Pull request by jpalmieri**
Clean 'er up to be submitted to the app marketplace.

I went by this guide: https://support.zendesk.com/hc/en-us/articles/204578883

Also added a feature: random congrats gifs

@PolRod if you have a sec to look, awesome. If not, all good.

### CODE REVIEW

**Comment by PolRod** [comment]
Will having all those gifs affect the load times of the app? If not, looks good to me!

**Comment by jpalmieri** [comment]
It probably will...but maybe they'll be cached after the app is loaded once? I'll investigate further.

Regardless, it's probably better to only have them load on the congrats view; I'll add that change.

**Comment by jpalmieri** [comment]
@PolRod FYI: it actually won't let me upload the app to ZD. The max size is 7mb :disappointed:

**Comment by jpalmieri** [comment]
@PolRod do you think this works? I guess it's ultimately up to the ZD gods

**Comment by jpalmieri** [comment]
@PolRod it does affect the load time of the app, but only when it's in congrats mode, so I guess the user could change their goal if they didn't want to see it. Maybe a future version could use a "don't show this again" checkbox or something, which was stored in localStorage as well.

Also, I think I'm going to open a personal storage facility called localStorage

**Comment by PolRod** [comment]
I think it looks good! I like the localStorage solution to the extra loading and the localStorage idea. VEry locally sourced.

**Pull request merged**
